# Generated by Django 3.2.2 on 2021-06-05 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=40)),
                ('gprice', models.IntegerField()),
                ('gquantity', models.IntegerField()),
                ('gseller', models.CharField(max_length=40)),
            ],
        ),
    ]
