# Generated by Django 3.2.2 on 2021-06-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='gming',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
